### ISSUE TITLE
Softlock(?) after second word in Monochrome

### ISSUE THREAD

**Issue by TheLemon27** [Starmapo/Lullaby-Forever-Fix#4]
Somehow, I've now had a problem with all 3 lost silver songs lol.
But yeah, the game didn't hard crash like last time, instead it got stuck during the second word you're supposed to type. Also the arrows, health bar, score bar and silver are gone.
I wouldn't call it a freeze either, since the unown letters are still moving and so is the fps counter, so i'd classify this as a softlock.
Screenshot of what I see below.
![monochrome softlock](https://github.com/Starmapo/Lullaby-Forever-Fix/assets/44980845/3bede641-6819-4336-a939-31273158bd22)

**Comment by TheLemon27** [comment]
ok, nvm, i finished the word and it just showed silver fade into darkness before booting me back to the story menu.
i checked in freeplay, and the song's still locked, so i didn't beat it.
so it aint a softlock, but somehing else

**Comment by Starmapo** [comment]
Turns out the reset keybind was still being checked for even while you had to type for Unown, so you'd accidentally reset if you had to press R or whatever your reset bind was, which checks out with the word you show in the screenshot. I must've been REALLY unlucky to not get any words with R in the one try I did during testing lol. I think the source code must be at least a bit outdated since this doesn't happen on the leaked build.

This will be fixed in the next update, thanks for reporting it 👍
